#!/bin/sh


user=$(whoami)
nl=$(cat /etc/crontab | grep -c 'nearest')
if [ "$nl" -eq 0 ]
then
	echo "0  9  * * * $user nearest" | sudo tee -a /etc/crontab >/dev/null 2>&1
fi

sudo touch ~ChiefCommander/nearest10.txt

Date=$(date -I -d "-1 day")

awk 'FNR==NR{a[$2]=$3;next} {if(a[$2] == "YES" && substr($1,2,10) == Date && substr($2,1,4) == "Army") {print Date,$2,((substr($3,4)-28.7041)^2+(substr($4,4)-77.1025)^2)}}' Date="$Date" attendance.log position.log | sort -g -k 3 | head -n 10 | awk '{print $1,$2}' | sudo tee -a ~ChiefCommander/nearest10.txt  # >/dev/null 2>&1
